apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: default
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  selector:
    prometheus: prometheus